In [5]:
# Question 1
from array import *
array_num = array('i', [1, 3, 5, 3, 7, 1, 9, 3])
print("Original array: "+str(array_num))
num_list = array_num.tolist()
print("Convert the said array to an ordinary list with the same items:")
print(num_list)

Original array: array('i', [1, 3, 5, 3, 7, 1, 9, 3])
Convert the said array to an ordinary list with the same items:
[1, 3, 5, 3, 7, 1, 9, 3]


In [6]:
# Question 2
import numpy as np
m = np.arange(6).reshape(2,3)
print("Original matrix:")
print(m)
result =  np.trace(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[0 1 2]
 [3 4 5]]
Condition number of the said matrix:
4


In [7]:
# Question 3
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [8]:
# Question 5
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.05089128 0.79587618 0.11277429 0.53599272 0.52630909 0.76226764
  0.06453707 0.46602611 0.99974836 0.10691592]
 [0.64396053 0.59723872 0.95511353 0.98655244 0.25552847 0.95352927
  0.67088608 0.6275716  0.08753156 0.74607902]
 [0.10452398 0.83756979 0.12963563 0.67014867 0.87526399 0.58502979
  0.41162375 0.56015697 0.10205558 0.46713449]
 [0.01011296 0.99639449 0.79321878 0.21776488 0.75419934 0.99188483
  0.15992224 0.28947508 0.46816981 0.62276745]
 [0.44868388 0.98075511 0.38930017 0.42393468 0.96924847 0.58499214
  0.22209022 0.90386866 0.9079635  0.50844715]]

Subtract the mean of each row of the said matrix:

[[-0.39124259  0.35374231 -0.32935957  0.09385885  0.08417523  0.32013377
  -0.3775968   0.02389225  0.55761449 -0.33521795]
 [-0.00843859 -0.0551604   0.30271441  0.33415332 -0.39687066  0.30113015
   0.01848696 -0.02482752 -0.56486757  0.0936799 ]
 [-0.36979028  0.36325553 -0.34467864  0.1958344   0.40094972  0.11071553
  -0.06269051  0.08584271 -0.3